### ISSUE TITLE
Using with Leaflet.Draw is causing error

### ISSUE THREAD

**Issue by KrishnaPG** [oliverroick/Leaflet.Deflate#28]
I am trying to show user drawn items as markers. The `L.Control.Draw` plugin works with `featureGroup`. When I replace the featureGroup with `L.Deflate` as shown below, it is giving error.
````
	let userDrawnItems = new L.Deflate({}).addTo(map);
	map.addControl(new L.Control.Draw({
			edit: {
					featureGroup: userDrawnItems,
					poly: {
							allowIntersection: true
					}
			},
			draw: {
					polygon: {
						allowIntersection: true,
						},
					}
			}
	}));	
````
Error:
![image](https://user-images.githubusercontent.com/4610831/33159826-e1617ca4-d03c-11e7-9246-328bf6d83f17.png)

````
main.js:6 Error:  Error: options.featureGroup must be a L.FeatureGroup
    at e.initialize (leaflet.draw.js:9)
    at new e (leaflet.js:5)
    at e.getModeHandlers (leaflet.draw.js:9)
    at e.addToolbar (leaflet.draw.js:9)
````

In the Deflate source code, If I change this [https://github.com/oliverroick/Leaflet.Deflate/blob/master/src/L.Deflate.js#L1](https://github.com/oliverroick/Leaflet.Deflate/blob/master/src/L.Deflate.js#L1) from 
````
L.Deflate = L.LayerGroup.extend({
````
to
````
L.Deflate = L.FeatureGroup.extend({
````
it works fine.

Since FeatureGroup extends from LayerGroup in leaflet, using this by default should be good option. Perhaps you can consider this in the upcoming release, unless it contradicts with any other issues.

**Comment by oliverroick** [comment]
Hi @KrishnaPG,

thanks for your report. I think it makes sense to extend from `FeatureGroup` instead of `LayerGroup`. The [tests pass](https://travis-ci.org/oliverroick/Leaflet.Deflate/builds/306691808) with your suggested changes. 

I'll give it a more thorough review soon, but I think there are good chances this will go into the next release.

**Comment by KrishnaPG** [comment]
Thanks @oliverroick

**Comment by oliverroick** [comment]
Reopening, or I'll forget about it...

**Comment by KrishnaPG** [comment]
No problem. Thanks. This library / plugin is a good work, by the way.

**Comment by oliverroick** [comment]
Hey @KrishnaPG,

Did you manage to get a fully working example where `L.Deflate` is extended from `L.FeatureGroup`, which also allows editing and adding via `Leaflet.Draw`.

I'm having trouble putting together a working example.  The problem seems to be that I'm using a [nested `FeatureGroup`](https://github.com/oliverroick/Leaflet.Deflate/blob/master/src/L.Deflate.js#L11) inside `L.Deflate` to hold all markers and polygons currently displayed on the map.

`Leaflet.Draw` doesn't seem to know where to find geometries to edit or where to put new geometries. When I reference the `_featureGroup` directly editing works but adding new geometries does not:

```javascript
var features = L.deflate({minSize: 20});
features.addTo(map);
var drawControl = new L.Control.Draw({
    edit: {
        featureGroup: features._featureGroup
    }
});
map.addControl(drawControl);
```

Looks like `L.Deflate` needs a fair bit of refactoring to make this work.

**Comment by KrishnaPG** [comment]
You are fairly close. Just need to add the event handlers for the Draw events, such as
````
map.on(L.Draw.Event.CREATED, function(event){
   // call your addLayer() method from here to add this drawn object to the markers
   Console.log('new object created');
});

    map.on(L.Draw.Event.DELETED, function(event){
        const deletedLayers = event.layers;
        const userDrawnItems = event.target.userDrawnItems;
        const visibleDrawnItems = event.target.visibleDrawnItems;
        deletedLayers.eachLayer(l => {
               // remove the layer "l" from the featureGroup of markers as well as other book keepting data
        })
    });
    // map.on(L.Draw.Event.DELETESTART, function(event){
    //  console.log("delete start", event);
    // })   
    // map.on(L.Draw.Event.DELETESTOP, function(event){
    //  console.log("delete stop", event);
    // })
    // map.userDrawnItems.on('layerremove', function(event){
    //  console.log("layer remove userdrawn: ", event);
    // })
````

**Comment by oliverroick** [comment]
I've got a basic example working; see [`example/leaflet-draw.html`](https://github.com/oliverroick/Leaflet.Deflate/blob/master/example/leaflet-draw.html).

This works as long as you don't zoom the map while editing. If you zoom, there are errors when `L.Deflate` tries to remove the marker from the map and the original features are sometimes misplaced. I need to dig a bit deeper into `Leaflet.Draw` to understand what's causing the errors. 

I'll be offline for a few weeks now; hopefully, I get to it early next year.
