### ISSUE TITLE
Leaflet.Deflate with a custom CRS map crashes application with *some* GeoJSON features

### ISSUE THREAD

**Issue by vobango** [oliverroick/Leaflet.Deflate#86]
Sorry if the title is a bit ambiguous but I couldn't come up with a better one since I can't exactly pinpoint the issue.
The problem is when I use L.Deflate with GeoJSON data on a map with a custom projection definition (EPSG:3301) _some_ features crash the application completely (as in no error/stack trace, the app just does not load).
Unfortunately I haven't been able to determine what is the common characteristic of the features that cause the crash nor where in the code the crash happens.

I made a codesandbox which recreates the problem and also shows both working and broken features: https://codesandbox.io/s/react-leaflet-dzvz2
(The sandbox does use react-leaflet and react-leaflet-deflate but I'm fairly sure it's not the react wrapper on L.Deflate that's causing the issue although if you prove me wrong I'm happy aswell).

Any insight into what is happening here is greatly appreciated.

**Comment by oliverroick** [comment]
Hi @vobango, I can confirm this is broken. I've never tested this using a custom projection; I need to make some time to look into this further. I this point I don't know what's going on.

**Comment by oliverroick** [comment]
Hi @vobango,

first of all, sorry for the overly long wait. Life got in the way; in-between starting a new job and moving countries I didn't get look at your problem earlier. 

It looks like I found the culprit. L.deflate uses the width and height of a feature's bounding box to work out when to deflate. For some reason, the bounding box of the last feature in your `broken` array had negative `width` and `height`.

The loop to find the deflate threshold runs forever because it never finds the threshold zoom level. It goes from negative to further negative, when it actually should find two values > 20px. 

Wrapping the calculation of `width` and `height` in `Math.abs` fixes this. I'd still like to understand how we end up width negative values, but that is for another day.

I'm planning to make a release soon; hoping this is still useful to you. Again, apologies for the long wait.

**Comment by mountaintwig** [comment]
I just stumbled upon this same issue. The second while loop inside _getZoomThreshold ran indefinetly while trying negative zoom levels. This happend even though the [above ](https://github.com/oliverroick/Leaflet.Deflate/issues/86#issuecomment-573872602) fix was present in the code.

Applying a break in the mentioned while loop seems to fix the problem:
```javascript
_getZoomThreshold: function (path) {
    let zoomThreshold;
    let zoom = this._map.getZoom();
    if (this._isCollapsed(path, this._map.getZoom())) {
      while (!zoomThreshold) {
        zoom += 1;
        if (!this._isCollapsed(path, zoom)) {
          zoomThreshold = zoom - 1;
        }
      }
    } else {
      while (!zoomThreshold) {
        // break if zoom is below zero to avoid infinit loop
        if (zoom < 0) {
            zoomThreshold = -1;
            break;
        }
        zoom -= 1;
        if (this._isCollapsed(path, zoom)) {
          zoomThreshold = zoom;
        }
      }
    }
    return zoomThreshold;
  }
```

**Comment by oliverroick** [comment]
@mountaintwig Can you send me an example of(of JSFiddle or Codesandbox or so) so I can reproduce the issue you're seeing?
